# The Flask session-signing secret. Generated by Terraform, stored only
# in Secrets Manager and in Terraform state (state itself should live in
# an encrypted S3 backend — see backend.tf.example — never in git).
resource "random_password" "flask_secret_key" {
  length  = 64
  special = false
}

resource "aws_secretsmanager_secret" "flask_secret_key" {
  name                    = "${var.project_name}/flask-secret-key"
  recovery_window_in_days = 0 # fine for a learning project; raise this for anything real
  tags                    = { Name = "${var.project_name}-flask-secret-key" }
}

resource "aws_secretsmanager_secret_version" "flask_secret_key" {
  secret_id     = aws_secretsmanager_secret.flask_secret_key.id
  secret_string = random_password.flask_secret_key.result
}

# Note: the RDS master password does NOT need a secret of its own here —
# aws_db_instance.notes.manage_master_user_password creates and manages
# that one automatically (see rds.tf and outputs.tf).
